.\" Process this file with
.\" groff -man -Tascii cpdf.1
.\"
.TH CPDF 1 "FEBRUARY 2024" "" ""
.SH NAME
cpdf \- PDF command line tools
.SH SYNOPSIS
.B cpdf
<input> <input> ... [-o <output>] <other parameters>
.SH DESCRIPTION
.B cpdf
provides various tools for modifying PDF files. The full documentation is given in the PDF file 
.B cpdfmanual.pdf.
.SH OPTIONS
.IP -version
Print the
.B cpdf
version number.
.IP "-help, --help"
Output a list of
.B cpdf
commands.
.SH AUTHOR
John Whitington <john at coherentgraphics dot co dot uk>
